language: c++
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script: 
  - cmake -DBENCHMARK_ENABLE_TESTING=OFF -DCMAKE_CXX_COMPILER=/usr/bin/g++-7 -DCMAKE_CC_COMPILER=/usr/bin/gcc-7 .
  - cmake --build tests
  - ./tests/tests


